# Generated by Django 5.2.1 on 2025-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0005_readmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmsg',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
